# Generated by Django 5.1.1 on 2024-09-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_init", "0004_entrada"),
    ]

    operations = [
        migrations.CreateModel(
            name="FotoPerfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foto_perfil",
                    models.ImageField(
                        blank=True, null=True, upload_to="perfil_usuario"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="entrada",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="upload_to_assunto"
            ),
        ),
    ]
